version: '3.8'
services:
  web:
    build:
      context: ./apache/docker
      dockerfile: Dockerfile
      args:
        WEB_ROOT_DIRECTORY: $WEB_ROOT_DIRECTORY
        WEB_DOMAIN: $WEB_DOMAIN
        WEB_HOST_PORTNUM: $WEB_HOST_PORTNUM
        WEB_CONTAINER_PORTNUM: $WEB_CONTAINER_PORTNUM
        WEB_HOST_PORTSSL: $WEB_HOST_PORTSSL
        WEB_CONTAINER_PORTSSL: $WEB_CONTAINER_PORTSSL
    labels:
      lap.taiji.perl: "Taiji Perl"
    volumes:
      # workspace
      - ./workspace:/workspace
      # docker settings template
      - ./template:/template
      # apache conf.d
      - ./apache/confd:/etc/httpd/conf.d
      # apache log
      - ./apache/log:/var/log/httpd
      # apache virtual host
      - ./apache/www:/var/www/$WEB_ROOT_DIRECTORY/web
      # SSL
      - ./cert:/etc/ssl/private/
    tty: true
    ports:
       - "$WEB_HOST_PORTNUM:$WEB_CONTAINER_PORTNUM"
       - "$WEB_HOST_PORTSSL:$WEB_CONTAINER_PORTSSL"
    entrypoint: bash -c "bash /workspace/entrypoint.sh $WEB_ROOT_DIRECTORY $WEB_DOMAIN $WEB_HOST_PORTNUM $WEB_CONTAINER_PORTNUM $WEB_HOST_PORTSSL $WEB_CONTAINER_PORTSSL && /bin/bash"